services:
  web:
    # Сборка на основе Dockerfile
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    # Контейнеры приложения и СУБД будут в одной сети
    networks:
      - fastapi-taskman-network
  db:
    image: postgres:12.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    networks:
      - fastapi-taskman-network
networks:
  fastapi-taskman-network:
    driver: bridge
volumes:
  postgres_data: